<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8">
    <title>Rekap Absensi Bulanan</title>
    <style>
    body {
        font-family: Arial, sans-serif;
        font-size: 12px;
        margin: 20px;
        color: #333;
    }

    h1 {
        text-align: center;
        font-size: 18px;
        color: #28a745;
        margin-bottom: 5px;
    }

    h3 {
        text-align: center;
        font-size: 14px;
        color: #555;
        margin-top: 0;
        margin-bottom: 20px;
    }

    table {
        border-collapse: collapse;
        width: 100%;
        margin-bottom: 15px;
    }

    th,
    td {
        border: 1px solid #000;
        padding: 6px;
        text-align: center;
    }

    th {
        background-color: #28a745;
        color: #fff;
    }

    .catatan {
        font-size: 11px;
        color: #555;
        padding: 6px;
    }

    .footer {
        margin-top: 30px;
        font-size: 11px;
        color: #555;
        text-align: center;
    }
    </style>
</head>

<body>
    <!-- Header -->
    <h1>Rekap Absensi Bulanan</h1>
    <h3>Bulan: {{ \Carbon\Carbon::parse($tanggal)->translatedFormat('F Y') }}</h3>

    <!-- Tabel Absensi -->
    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Jumlah Hadir</th>
                <th>Jumlah Tidak Hadir</th>
                <th>Total Hari</th>
            </tr>
        </thead>
        <tbody>
            @foreach($rekapAbsensi as $index => $k)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $k->nama }}</td>
                <td>{{ $k->jumlah_hadir }}</td>
                <td>{{ $k->jumlah_tidak_hadir }}</td>
                <td>{{ $k->total_hari }}</td>
            </tr>
            @endforeach

            @if($rekapAbsensi->isEmpty())
            <tr>
                <td colspan="5">Belum ada data rekap bulanan.</td>
            </tr>
            @endif
        </tbody>
    </table>

    <!-- Catatan -->
    <div class="catatan">
        📌 Catatan: Rekap ini hanya menghitung karyawan yang hadir. Status izin, sakit, atau alpha dianggap tidak hadir.
        Pastikan semua data absensi harian sudah terinput dengan benar.
    </div>

    <!-- Footer -->
    <div class="footer">
        Generated by Sistem Absensi SPPG - {{ \Carbon\Carbon::now()->translatedFormat('d F Y') }}
    </div>
</body>

</html>